-- MySQL Script generated by MySQL Workbench
-- Thu Dec  4 17:51:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`petowners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`petowners` (
  `owner_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  PRIMARY KEY (`owner_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pets` (
  `pet_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `species` VARCHAR(45) NULL,
  `breed` VARCHAR(45) NULL,
  `PetOwners_owner_id` INT NOT NULL,
  PRIMARY KEY (`pet_id`),
  INDEX `fk_pets_PetOwners_idx` (`PetOwners_owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_pets_PetOwners`
    FOREIGN KEY (`PetOwners_owner_id`)
    REFERENCES `mydb`.`petowners` (`owner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rooms` (
  `room_id` INT NOT NULL AUTO_INCREMENT,
  `roomNumber` VARCHAR(45) NULL,
  `roomType` VARCHAR(45) NULL,
  `pricePerNight` DECIMAL(10,2) NULL,
  PRIMARY KEY (`room_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservations` (
  `reservations_id` INT NOT NULL AUTO_INCREMENT,
  `startDate` DATE NULL,
  `endDate` DATE NULL,
  `pets_pet_id` INT NOT NULL,
  `rooms_room_id` INT NOT NULL,
  PRIMARY KEY (`reservations_id`),
  INDEX `fk_reservations_pets1_idx` (`pets_pet_id` ASC) VISIBLE,
  INDEX `fk_reservations_rooms1_idx` (`rooms_room_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservations_pets1`
    FOREIGN KEY (`pets_pet_id`)
    REFERENCES `mydb`.`pets` (`pet_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservations_rooms1`
    FOREIGN KEY (`rooms_room_id`)
    REFERENCES `mydb`.`rooms` (`room_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`services` (
  `service_id` INT NOT NULL AUTO_INCREMENT,
  `serviceName` VARCHAR(45) NULL,
  `servicePrice` DECIMAL(10,2) NULL,
  `reservations_reservations_id` INT NOT NULL,
  PRIMARY KEY (`service_id`),
  INDEX `fk_services_reservations1_idx` (`reservations_reservations_id` ASC) VISIBLE,
  CONSTRAINT `fk_services_reservations1`
    FOREIGN KEY (`reservations_reservations_id`)
    REFERENCES `mydb`.`reservations` (`reservations_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
